name: yanci
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  dio: ^5.6.0
  google_fonts: ^6.2.1
  new_version_plus: ^0.0.11
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  encrypt: ^5.0.3
  tuple: ^2.0.2
  crypto: ^3.0.5
  cached_network_image: ^3.4.0
  share_plus: ^10.0.0
  url_launcher: ^6.3.0
  firebase_auth:
  connectivity_plus: ^6.0.5
  smooth_page_indicator: ^1.2.0+3
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  country_code_picker: ^3.0.0
  signature: ^5.5.0
  pinput: ^5.0.0
  intl: ^0.19.0
  flutter_slidable: ^3.1.1
  fl_chart: ^0.69.0
  custom_syncfusion_flutter_charts: ^1.0.1
  stacked_firebase_auth: ^2.20.1
  firebase_core: ^3.4.0
  flutter_image_compress: ^2.3.0
  flutter_cached_pdfview: ^0.4.2
  dropdown_flutter: ^1.0.1
  dropdown_search: ^5.0.6
  flutter_local_notifications: ^17.2.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  open_file: ^3.5.3


dev_dependencies:
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.7.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottiefiles/
    - assets/svg/
