///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FaqModelData {
/*
{
  "_id": "66d04e39830d1c4fe1b689f3",
  "question": "How do I reset my password?",
  "type": "Account",
  "answer": "To reset your password, click on 'Forgot Password' at the login page and follow the instructions.",
  "status": "LIVE",
  "createdAt": "2024-08-29T10:32:25.152Z",
  "updatedAt": "2024-08-29T10:32:25.152Z"
}
*/

  String? Id;
  String? question;
  String? type;
  String? answer;
  String? status;
  String? createdAt;
  String? updatedAt;

  FaqModelData({
    this.Id,
    this.question,
    this.type,
    this.answer,
    this.status,
    this.createdAt,
    this.updatedAt,
  });
  FaqModelData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    question = json['question']?.toString();
    type = json['type']?.toString();
    answer = json['answer']?.toString();
    status = json['status']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['question'] = question;
    data['type'] = type;
    data['answer'] = answer;
    data['status'] = status;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class FaqModel {
/*
{
  "data": [
    {
      "_id": "66d04e39830d1c4fe1b689f3",
      "question": "How do I reset my password?",
      "type": "Account",
      "answer": "To reset your password, click on 'Forgot Password' at the login page and follow the instructions.",
      "status": "LIVE",
      "createdAt": "2024-08-29T10:32:25.152Z",
      "updatedAt": "2024-08-29T10:32:25.152Z"
    }
  ],
  "message": "faqs retrived successfully",
  "status": true
}
*/

  List<FaqModelData>? data;
  String? message;
  bool? status;

  FaqModel({
    this.data,
    this.message,
    this.status,
  });
  FaqModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <FaqModelData>[];
      v.forEach((v) {
        arr0.add(FaqModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
