///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserInfoModelDataPassportPic {
/*
{
  "key": "public/passportPictures/041dd2f9-75e9-4b98-8a85-e468986d1aa8",
  "url": "https://yanci-uploads.s3.us-east-2.amazonaws.com/public/passportPictures/041dd2f9-75e9-4b98-8a85-e468986d1aa8",
  "_id": "6696179a7d6fdec557143e4e"
}
*/

  String? key;
  String? url;
  String? Id;

  UserInfoModelDataPassportPic({
    this.key,
    this.url,
    this.Id,
  });
  UserInfoModelDataPassportPic.fromJson(Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    data['_id'] = Id;
    return data;
  }
}

class UserInfoModelDataSignature {
/*
{
  "key": "public/signatureImages/2a93893b-7a28-4b83-b5dc-d87df212e53d-signature",
  "url": "https://pricebutlers.s3.us-east-2.amazonaws.com/public/signatureImages/2a93893b-7a28-4b83-b5dc-d87df212e53d-signature",
  "_id": "6687c424512d0ceeacc93170"
}
*/

  String? key;
  String? url;
  String? Id;

  UserInfoModelDataSignature({
    this.key,
    this.url,
    this.Id,
  });
  UserInfoModelDataSignature.fromJson(Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    data['_id'] = Id;
    return data;
  }
}

class UserInfoModelDataCdsForm {
/*
{
  "key": "public/csd_forms/419ebe2c-e80e-406c-9f40-64abf70a9a8c",
  "url": "https://yanci-uploads.s3.us-east-2.amazonaws.com/public/csd_forms/419ebe2c-e80e-406c-9f40-64abf70a9a8c",
  "_id": "66966f44984584adb6f3f70c"
}
*/

  String? key;
  String? url;
  String? Id;

  UserInfoModelDataCdsForm({
    this.key,
    this.url,
    this.Id,
  });
  UserInfoModelDataCdsForm.fromJson(Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    data['_id'] = Id;
    return data;
  }
}

class UserInfoModelDataPreferences {
/*
{
  "notificationEnabled": false,
  "locationShared": false,
  "_id": "6685028a6d26699091240d10"
}
*/

  bool? notificationEnabled;
  bool? locationShared;
  String? Id;

  UserInfoModelDataPreferences({
    this.notificationEnabled,
    this.locationShared,
    this.Id,
  });
  UserInfoModelDataPreferences.fromJson(Map<String, dynamic> json) {
    notificationEnabled = json['notificationEnabled'];
    locationShared = json['locationShared'];
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['notificationEnabled'] = notificationEnabled;
    data['locationShared'] = locationShared;
    data['_id'] = Id;
    return data;
  }
}

class UserInfoModelData {
/*
{
  "_id": "6685028a6d26699091240d11",
  "email": "amar@ideausher.com",
  "profilePic": "",
  "dob": "2002-07-01T00:00:00.000Z",
  "firebaseUid": "8p4r0wY1IGaNowTXueCvIDT7iI53",
  "firebaseSignInProvider": "google.com",
  "isBlocked": false,
  "isDeleted": false,
  "preferences": {
    "notificationEnabled": false,
    "locationShared": false,
    "_id": "6685028a6d26699091240d10"
  },
  "createdAt": "2024-07-03T07:49:30.611Z",
  "updatedAt": "2024-07-17T11:11:23.053Z",
  "__v": 0,
  "cdsForm": {
    "key": "public/csd_forms/419ebe2c-e80e-406c-9f40-64abf70a9a8c",
    "url": "https://yanci-uploads.s3.us-east-2.amazonaws.com/public/csd_forms/419ebe2c-e80e-406c-9f40-64abf70a9a8c",
    "_id": "66966f44984584adb6f3f70c"
  },
  "firstName": "Amar",
  "gender": "Male",
  "lastName": "Parsad",
  "maritalStatus": "Single",
  "nationality": "Azerbaijani",
  "originCountry": "Bahamas",
  "personalWithAddressInfo": true,
  "proofInfo": true,
  "bankingInfo": true,
  "investmentInfo": true,
  "beneficiaryInfo": true,
  "signature": {
    "key": "public/signatureImages/2a93893b-7a28-4b83-b5dc-d87df212e53d-signature",
    "url": "https://pricebutlers.s3.us-east-2.amazonaws.com/public/signatureImages/2a93893b-7a28-4b83-b5dc-d87df212e53d-signature",
    "_id": "6687c424512d0ceeacc93170"
  },
  "signatureInfo": true,
  "investorInfo": true,
  "pinNumber": 1234,
  "pinNumberInfo": true,
  "generatedCds": true,
  "passportPic": {
    "key": "public/passportPictures/041dd2f9-75e9-4b98-8a85-e468986d1aa8",
    "url": "https://yanci-uploads.s3.us-east-2.amazonaws.com/public/passportPictures/041dd2f9-75e9-4b98-8a85-e468986d1aa8",
    "_id": "6696179a7d6fdec557143e4e"
  },
  "residentialStatus": "Non-resident Ghanaian",
  "title": "Mr.",
  "policyVersion": 2,
  "termsVersion": 2
}
*/

  String? Id;
  String? email;
  String? profilePic;
  String? dob;
  String? firebaseUid;
  String? firebaseSignInProvider;
  bool? isBlocked;
  bool? isDeleted;
  UserInfoModelDataPreferences? preferences;
  String? createdAt;
  String? updatedAt;
  UserInfoModelDataCdsForm? cdsForm;
  String? firstName;
  String? gender;
  String? lastName;
  String? maritalStatus;
  String? nationality;
  String? originCountry;
  bool? personalWithAddressInfo;
  bool? proofInfo;
  bool? bankingInfo;
  bool? investmentInfo;
  bool? beneficiaryInfo;
  UserInfoModelDataSignature? signature;
  bool? signatureInfo;
  bool? investorInfo;
  int? pinNumber;
  bool? pinNumberInfo;
  bool? generatedCds;
  UserInfoModelDataPassportPic? passportPic;
  String? residentialStatus;
  String? title;
  int? policyVersion;
  int? termsVersion;

  UserInfoModelData({
    this.Id,
    this.email,
    this.profilePic,
    this.dob,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.isBlocked,
    this.isDeleted,
    this.preferences,
    this.createdAt,
    this.updatedAt,
    this.cdsForm,
    this.firstName,
    this.gender,
    this.lastName,
    this.maritalStatus,
    this.nationality,
    this.originCountry,
    this.personalWithAddressInfo,
    this.proofInfo,
    this.bankingInfo,
    this.investmentInfo,
    this.beneficiaryInfo,
    this.signature,
    this.signatureInfo,
    this.investorInfo,
    this.pinNumber,
    this.pinNumberInfo,
    this.generatedCds,
    this.passportPic,
    this.residentialStatus,
    this.title,
    this.policyVersion,
    this.termsVersion,
  });
  UserInfoModelData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    email = json['email']?.toString();
    profilePic = json['profilePic']?.toString();
    dob = json['dob']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    isBlocked = json['isBlocked'];
    isDeleted = json['isDeleted'];
    preferences = (json['preferences'] != null) ? UserInfoModelDataPreferences.fromJson(json['preferences']) : null;
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    cdsForm = (json['cdsForm'] != null) ? UserInfoModelDataCdsForm.fromJson(json['cdsForm']) : null;
    firstName = json['firstName']?.toString();
    gender = json['gender']?.toString();
    lastName = json['lastName']?.toString();
    maritalStatus = json['maritalStatus']?.toString();
    nationality = json['nationality']?.toString();
    originCountry = json['originCountry']?.toString();
    personalWithAddressInfo = json['personalWithAddressInfo'];
    proofInfo = json['proofInfo'];
    bankingInfo = json['bankingInfo'];
    investmentInfo = json['investmentInfo'];
    beneficiaryInfo = json['beneficiaryInfo'];
    signature = (json['signature'] != null) ? UserInfoModelDataSignature.fromJson(json['signature']) : null;
    signatureInfo = json['signatureInfo'];
    investorInfo = json['investorInfo'];
    pinNumber = json['pinNumber']?.toInt();
    pinNumberInfo = json['pinNumberInfo'];
    generatedCds = json['generatedCds'];
    passportPic = (json['passportPic'] != null) ? UserInfoModelDataPassportPic.fromJson(json['passportPic']) : null;
    residentialStatus = json['residentialStatus']?.toString();
    title = json['title']?.toString();
    policyVersion = json['policyVersion']?.toInt();
    termsVersion = json['termsVersion']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['email'] = email;
    data['profilePic'] = profilePic;
    data['dob'] = dob;
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['isBlocked'] = isBlocked;
    data['isDeleted'] = isDeleted;
    if (preferences != null) {
      data['preferences'] = preferences!.toJson();
    }
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    if (cdsForm != null) {
      data['cdsForm'] = cdsForm!.toJson();
    }
    data['firstName'] = firstName;
    data['gender'] = gender;
    data['lastName'] = lastName;
    data['maritalStatus'] = maritalStatus;
    data['nationality'] = nationality;
    data['originCountry'] = originCountry;
    data['personalWithAddressInfo'] = personalWithAddressInfo;
    data['proofInfo'] = proofInfo;
    data['bankingInfo'] = bankingInfo;
    data['investmentInfo'] = investmentInfo;
    data['beneficiaryInfo'] = beneficiaryInfo;
    if (signature != null) {
      data['signature'] = signature!.toJson();
    }
    data['signatureInfo'] = signatureInfo;
    data['investorInfo'] = investorInfo;
    data['pinNumber'] = pinNumber;
    data['pinNumberInfo'] = pinNumberInfo;
    data['generatedCds'] = generatedCds;
    if (passportPic != null) {
      data['passportPic'] = passportPic!.toJson();
    }
    data['residentialStatus'] = residentialStatus;
    data['title'] = title;
    data['policyVersion'] = policyVersion;
    data['termsVersion'] = termsVersion;
    return data;
  }
}

class UserInfoModel {
/*
{
  "status": true,
  "data": {
    "_id": "6685028a6d26699091240d11",
    "email": "amar@ideausher.com",
    "profilePic": "",
    "dob": "2002-07-01T00:00:00.000Z",
    "firebaseUid": "8p4r0wY1IGaNowTXueCvIDT7iI53",
    "firebaseSignInProvider": "google.com",
    "isBlocked": false,
    "isDeleted": false,
    "preferences": {
      "notificationEnabled": false,
      "locationShared": false,
      "_id": "6685028a6d26699091240d10"
    },
    "createdAt": "2024-07-03T07:49:30.611Z",
    "updatedAt": "2024-07-17T11:11:23.053Z",
    "__v": 0,
    "cdsForm": {
      "key": "public/csd_forms/419ebe2c-e80e-406c-9f40-64abf70a9a8c",
      "url": "https://yanci-uploads.s3.us-east-2.amazonaws.com/public/csd_forms/419ebe2c-e80e-406c-9f40-64abf70a9a8c",
      "_id": "66966f44984584adb6f3f70c"
    },
    "firstName": "Amar",
    "gender": "Male",
    "lastName": "Parsad",
    "maritalStatus": "Single",
    "nationality": "Azerbaijani",
    "originCountry": "Bahamas",
    "personalWithAddressInfo": true,
    "proofInfo": true,
    "bankingInfo": true,
    "investmentInfo": true,
    "beneficiaryInfo": true,
    "signature": {
      "key": "public/signatureImages/2a93893b-7a28-4b83-b5dc-d87df212e53d-signature",
      "url": "https://pricebutlers.s3.us-east-2.amazonaws.com/public/signatureImages/2a93893b-7a28-4b83-b5dc-d87df212e53d-signature",
      "_id": "6687c424512d0ceeacc93170"
    },
    "signatureInfo": true,
    "investorInfo": true,
    "pinNumber": 1234,
    "pinNumberInfo": true,
    "generatedCds": true,
    "passportPic": {
      "key": "public/passportPictures/041dd2f9-75e9-4b98-8a85-e468986d1aa8",
      "url": "https://yanci-uploads.s3.us-east-2.amazonaws.com/public/passportPictures/041dd2f9-75e9-4b98-8a85-e468986d1aa8",
      "_id": "6696179a7d6fdec557143e4e"
    },
    "residentialStatus": "Non-resident Ghanaian",
    "title": "Mr.",
    "policyVersion": 2,
    "termsVersion": 2
  }
}
*/

  bool? status;
  UserInfoModelData? data;

  UserInfoModel({
    this.status,
    this.data,
  });
  UserInfoModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    data = (json['data'] != null) ? UserInfoModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
