///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserInfoModelDataAddress {
/*
{
  "_id": "668691a8512d0ceeacc93113",
  "userId": "6685028a6d26699091240d11",
  "country": "India",
  "state": "Punjab",
  "city": "Bathinda",
  "address": "Phase 1",
  "latitude": "0.00",
  "longitude": "0.00",
  "createdAt": "2024-07-04T12:12:24.837Z",
  "updatedAt": "2024-07-16T06:48:29.373Z"
}
*/

  String? Id;
  String? userId;
  String? country;
  String? state;
  String? city;
  String? address;
  String? latitude;
  String? longitude;
  String? createdAt;
  String? updatedAt;

  UserInfoModelDataAddress({
    this.Id,
    this.userId,
    this.country,
    this.state,
    this.city,
    this.address,
    this.latitude,
    this.longitude,
    this.createdAt,
    this.updatedAt,
  });
  UserInfoModelDataAddress.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    userId = json['userId']?.toString();
    country = json['country']?.toString();
    state = json['state']?.toString();
    city = json['city']?.toString();
    address = json['address']?.toString();
    latitude = json['latitude']?.toString();
    longitude = json['longitude']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['userId'] = userId;
    data['country'] = country;
    data['state'] = state;
    data['city'] = city;
    data['address'] = address;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class UserInfoModelDataUserPassportPic {
/*
{
  "key": "public/passportPictures/041dd2f9-75e9-4b98-8a85-e468986d1aa8",
  "url": "https://yanci-uploads.s3.us-east-2.amazonaws.com/public/passportPictures/041dd2f9-75e9-4b98-8a85-e468986d1aa8",
  "_id": "6696179a7d6fdec557143e4e"
}
*/

  String? key;
  String? url;
  String? Id;

  UserInfoModelDataUserPassportPic({
    this.key,
    this.url,
    this.Id,
  });
  UserInfoModelDataUserPassportPic.fromJson(Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    data['_id'] = Id;
    return data;
  }
}

class UserInfoModelDataUserSignature {
/*
{
  "key": "public/signatureImages/2a93893b-7a28-4b83-b5dc-d87df212e53d-signature",
  "url": "https://pricebutlers.s3.us-east-2.amazonaws.com/public/signatureImages/2a93893b-7a28-4b83-b5dc-d87df212e53d-signature",
  "_id": "6687c424512d0ceeacc93170"
}
*/

  String? key;
  String? url;
  String? Id;

  UserInfoModelDataUserSignature({
    this.key,
    this.url,
    this.Id,
  });
  UserInfoModelDataUserSignature.fromJson(Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    data['_id'] = Id;
    return data;
  }
}

class UserInfoModelDataUserCdsForm {
/*
{
  "key": "public/csd_forms/419ebe2c-e80e-406c-9f40-64abf70a9a8c",
  "url": "https://yanci-uploads.s3.us-east-2.amazonaws.com/public/csd_forms/419ebe2c-e80e-406c-9f40-64abf70a9a8c",
  "_id": "66966f44984584adb6f3f70c"
}
*/

  String? key;
  String? url;
  String? Id;

  UserInfoModelDataUserCdsForm({
    this.key,
    this.url,
    this.Id,
  });
  UserInfoModelDataUserCdsForm.fromJson(Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    data['_id'] = Id;
    return data;
  }
}

class UserInfoModelDataUserPreferences {
/*
{
  "notificationEnabled": false,
  "locationShared": false,
  "_id": "6685028a6d26699091240d10"
}
*/

  bool? notificationEnabled;
  bool? locationShared;
  String? Id;

  UserInfoModelDataUserPreferences({
    this.notificationEnabled,
    this.locationShared,
    this.Id,
  });
  UserInfoModelDataUserPreferences.fromJson(Map<String, dynamic> json) {
    notificationEnabled = json['notificationEnabled'];
    locationShared = json['locationShared'];
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['notificationEnabled'] = notificationEnabled;
    data['locationShared'] = locationShared;
    data['_id'] = Id;
    return data;
  }
}

class UserInfoModelDataUser {
/*
{
  "_id": "6685028a6d26699091240d11",
  "email": "amar@ideausher.com",
  "profilePic": "",
  "dob": "2002-07-01T00:00:00.000Z",
  "firebaseUid": "8p4r0wY1IGaNowTXueCvIDT7iI53",
  "firebaseSignInProvider": "google.com",
  "isBlocked": false,
  "isDeleted": false,
  "preferences": {
    "notificationEnabled": false,
    "locationShared": false,
    "_id": "6685028a6d26699091240d10"
  },
  "createdAt": "2024-07-03T07:49:30.611Z",
  "updatedAt": "2024-08-30T11:02:18.690Z",
  "cdsForm": {
    "key": "public/csd_forms/419ebe2c-e80e-406c-9f40-64abf70a9a8c",
    "url": "https://yanci-uploads.s3.us-east-2.amazonaws.com/public/csd_forms/419ebe2c-e80e-406c-9f40-64abf70a9a8c",
    "_id": "66966f44984584adb6f3f70c"
  },
  "firstName": "Amar",
  "gender": "Male",
  "lastName": "Parsad",
  "maritalStatus": "Single",
  "nationality": "Azerbaijani",
  "originCountry": "Bahamas",
  "personalWithAddressInfo": true,
  "proofInfo": true,
  "bankingInfo": true,
  "investmentInfo": true,
  "beneficiaryInfo": true,
  "signature": {
    "key": "public/signatureImages/2a93893b-7a28-4b83-b5dc-d87df212e53d-signature",
    "url": "https://pricebutlers.s3.us-east-2.amazonaws.com/public/signatureImages/2a93893b-7a28-4b83-b5dc-d87df212e53d-signature",
    "_id": "6687c424512d0ceeacc93170"
  },
  "signatureInfo": true,
  "investorInfo": true,
  "pinNumber": 1234,
  "pinNumberInfo": true,
  "generatedCds": true,
  "passportPic": {
    "key": "public/passportPictures/041dd2f9-75e9-4b98-8a85-e468986d1aa8",
    "url": "https://yanci-uploads.s3.us-east-2.amazonaws.com/public/passportPictures/041dd2f9-75e9-4b98-8a85-e468986d1aa8",
    "_id": "6696179a7d6fdec557143e4e"
  },
  "residentialStatus": "Non-resident Ghanaian",
  "title": "Mr.",
  "policyVersion": 2,
  "termsVersion": 2,
  "status": "pending",
  "countryCode": "+233",
  "phone": "9041409384"
}
*/

  String? Id;
  String? email;
  String? profilePic;
  String? dob;
  String? firebaseUid;
  String? firebaseSignInProvider;
  bool? isBlocked;
  bool? isDeleted;
  UserInfoModelDataUserPreferences? preferences;
  String? createdAt;
  String? updatedAt;
  UserInfoModelDataUserCdsForm? cdsForm;
  String? firstName;
  String? gender;
  String? lastName;
  String? maritalStatus;
  String? nationality;
  String? originCountry;
  bool? personalWithAddressInfo;
  bool? proofInfo;
  bool? bankingInfo;
  bool? investmentInfo;
  bool? beneficiaryInfo;
  UserInfoModelDataUserSignature? signature;
  bool? signatureInfo;
  bool? investorInfo;
  int? pinNumber;
  bool? pinNumberInfo;
  bool? generatedCds;
  UserInfoModelDataUserPassportPic? passportPic;
  String? residentialStatus;
  String? title;
  int? policyVersion;
  int? termsVersion;
  String? status;
  String? countryCode;
  String? phone;

  UserInfoModelDataUser({
    this.Id,
    this.email,
    this.profilePic,
    this.dob,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.isBlocked,
    this.isDeleted,
    this.preferences,
    this.createdAt,
    this.updatedAt,
    this.cdsForm,
    this.firstName,
    this.gender,
    this.lastName,
    this.maritalStatus,
    this.nationality,
    this.originCountry,
    this.personalWithAddressInfo,
    this.proofInfo,
    this.bankingInfo,
    this.investmentInfo,
    this.beneficiaryInfo,
    this.signature,
    this.signatureInfo,
    this.investorInfo,
    this.pinNumber,
    this.pinNumberInfo,
    this.generatedCds,
    this.passportPic,
    this.residentialStatus,
    this.title,
    this.policyVersion,
    this.termsVersion,
    this.status,
    this.countryCode,
    this.phone,
  });
  UserInfoModelDataUser.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    email = json['email']?.toString();
    profilePic = json['profilePic']?.toString();
    dob = json['dob']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    isBlocked = json['isBlocked'];
    isDeleted = json['isDeleted'];
    preferences = (json['preferences'] != null) ? UserInfoModelDataUserPreferences.fromJson(json['preferences']) : null;
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    cdsForm = (json['cdsForm'] != null) ? UserInfoModelDataUserCdsForm.fromJson(json['cdsForm']) : null;
    firstName = json['firstName']?.toString();
    gender = json['gender']?.toString();
    lastName = json['lastName']?.toString();
    maritalStatus = json['maritalStatus']?.toString();
    nationality = json['nationality']?.toString();
    originCountry = json['originCountry']?.toString();
    personalWithAddressInfo = json['personalWithAddressInfo'];
    proofInfo = json['proofInfo'];
    bankingInfo = json['bankingInfo'];
    investmentInfo = json['investmentInfo'];
    beneficiaryInfo = json['beneficiaryInfo'];
    signature = (json['signature'] != null) ? UserInfoModelDataUserSignature.fromJson(json['signature']) : null;
    signatureInfo = json['signatureInfo'];
    investorInfo = json['investorInfo'];
    pinNumber = json['pinNumber']?.toInt();
    pinNumberInfo = json['pinNumberInfo'];
    generatedCds = json['generatedCds'];
    passportPic = (json['passportPic'] != null) ? UserInfoModelDataUserPassportPic.fromJson(json['passportPic']) : null;
    residentialStatus = json['residentialStatus']?.toString();
    title = json['title']?.toString();
    policyVersion = json['policyVersion']?.toInt();
    termsVersion = json['termsVersion']?.toInt();
    status = json['status']?.toString();
    countryCode = json['countryCode']?.toString();
    phone = json['phone']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['email'] = email;
    data['profilePic'] = profilePic;
    data['dob'] = dob;
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['isBlocked'] = isBlocked;
    data['isDeleted'] = isDeleted;
    if (preferences != null) {
      data['preferences'] = preferences!.toJson();
    }
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    if (cdsForm != null) {
      data['cdsForm'] = cdsForm!.toJson();
    }
    data['firstName'] = firstName;
    data['gender'] = gender;
    data['lastName'] = lastName;
    data['maritalStatus'] = maritalStatus;
    data['nationality'] = nationality;
    data['originCountry'] = originCountry;
    data['personalWithAddressInfo'] = personalWithAddressInfo;
    data['proofInfo'] = proofInfo;
    data['bankingInfo'] = bankingInfo;
    data['investmentInfo'] = investmentInfo;
    data['beneficiaryInfo'] = beneficiaryInfo;
    if (signature != null) {
      data['signature'] = signature!.toJson();
    }
    data['signatureInfo'] = signatureInfo;
    data['investorInfo'] = investorInfo;
    data['pinNumber'] = pinNumber;
    data['pinNumberInfo'] = pinNumberInfo;
    data['generatedCds'] = generatedCds;
    if (passportPic != null) {
      data['passportPic'] = passportPic!.toJson();
    }
    data['residentialStatus'] = residentialStatus;
    data['title'] = title;
    data['policyVersion'] = policyVersion;
    data['termsVersion'] = termsVersion;
    data['status'] = status;
    data['countryCode'] = countryCode;
    data['phone'] = phone;
    return data;
  }
}

class UserInfoModelData {
/*
{
  "user": {
    "_id": "6685028a6d26699091240d11",
    "email": "amar@ideausher.com",
    "profilePic": "",
    "dob": "2002-07-01T00:00:00.000Z",
    "firebaseUid": "8p4r0wY1IGaNowTXueCvIDT7iI53",
    "firebaseSignInProvider": "google.com",
    "isBlocked": false,
    "isDeleted": false,
    "preferences": {
      "notificationEnabled": false,
      "locationShared": false,
      "_id": "6685028a6d26699091240d10"
    },
    "createdAt": "2024-07-03T07:49:30.611Z",
    "updatedAt": "2024-08-30T11:02:18.690Z",
    "cdsForm": {
      "key": "public/csd_forms/419ebe2c-e80e-406c-9f40-64abf70a9a8c",
      "url": "https://yanci-uploads.s3.us-east-2.amazonaws.com/public/csd_forms/419ebe2c-e80e-406c-9f40-64abf70a9a8c",
      "_id": "66966f44984584adb6f3f70c"
    },
    "firstName": "Amar",
    "gender": "Male",
    "lastName": "Parsad",
    "maritalStatus": "Single",
    "nationality": "Azerbaijani",
    "originCountry": "Bahamas",
    "personalWithAddressInfo": true,
    "proofInfo": true,
    "bankingInfo": true,
    "investmentInfo": true,
    "beneficiaryInfo": true,
    "signature": {
      "key": "public/signatureImages/2a93893b-7a28-4b83-b5dc-d87df212e53d-signature",
      "url": "https://pricebutlers.s3.us-east-2.amazonaws.com/public/signatureImages/2a93893b-7a28-4b83-b5dc-d87df212e53d-signature",
      "_id": "6687c424512d0ceeacc93170"
    },
    "signatureInfo": true,
    "investorInfo": true,
    "pinNumber": 1234,
    "pinNumberInfo": true,
    "generatedCds": true,
    "passportPic": {
      "key": "public/passportPictures/041dd2f9-75e9-4b98-8a85-e468986d1aa8",
      "url": "https://yanci-uploads.s3.us-east-2.amazonaws.com/public/passportPictures/041dd2f9-75e9-4b98-8a85-e468986d1aa8",
      "_id": "6696179a7d6fdec557143e4e"
    },
    "residentialStatus": "Non-resident Ghanaian",
    "title": "Mr.",
    "policyVersion": 2,
    "termsVersion": 2,
    "status": "pending",
    "countryCode": "+233",
    "phone": "9041409384"
  },
  "address": {
    "_id": "668691a8512d0ceeacc93113",
    "userId": "6685028a6d26699091240d11",
    "country": "India",
    "state": "Punjab",
    "city": "Bathinda",
    "address": "Phase 1",
    "latitude": "0.00",
    "longitude": "0.00",
    "createdAt": "2024-07-04T12:12:24.837Z",
    "updatedAt": "2024-07-16T06:48:29.373Z"
  },
  "beneficiaryPhone": "9041409384"
}
*/

  UserInfoModelDataUser? user;
  UserInfoModelDataAddress? address;
  String? beneficiaryPhone;

  UserInfoModelData({
    this.user,
    this.address,
    this.beneficiaryPhone,
  });
  UserInfoModelData.fromJson(Map<String, dynamic> json) {
    user = (json['user'] != null) ? UserInfoModelDataUser.fromJson(json['user']) : null;
    address = (json['address'] != null) ? UserInfoModelDataAddress.fromJson(json['address']) : null;
    beneficiaryPhone = json['beneficiaryPhone']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (user != null) {
      data['user'] = user!.toJson();
    }
    if (address != null) {
      data['address'] = address!.toJson();
    }
    data['beneficiaryPhone'] = beneficiaryPhone;
    return data;
  }
}

class UserInfoModel {
/*
{
  "status": true,
  "data": {
    "user": {
      "_id": "6685028a6d26699091240d11",
      "email": "amar@ideausher.com",
      "profilePic": "",
      "dob": "2002-07-01T00:00:00.000Z",
      "firebaseUid": "8p4r0wY1IGaNowTXueCvIDT7iI53",
      "firebaseSignInProvider": "google.com",
      "isBlocked": false,
      "isDeleted": false,
      "preferences": {
        "notificationEnabled": false,
        "locationShared": false,
        "_id": "6685028a6d26699091240d10"
      },
      "createdAt": "2024-07-03T07:49:30.611Z",
      "updatedAt": "2024-08-30T11:02:18.690Z",
      "cdsForm": {
        "key": "public/csd_forms/419ebe2c-e80e-406c-9f40-64abf70a9a8c",
        "url": "https://yanci-uploads.s3.us-east-2.amazonaws.com/public/csd_forms/419ebe2c-e80e-406c-9f40-64abf70a9a8c",
        "_id": "66966f44984584adb6f3f70c"
      },
      "firstName": "Amar",
      "gender": "Male",
      "lastName": "Parsad",
      "maritalStatus": "Single",
      "nationality": "Azerbaijani",
      "originCountry": "Bahamas",
      "personalWithAddressInfo": true,
      "proofInfo": true,
      "bankingInfo": true,
      "investmentInfo": true,
      "beneficiaryInfo": true,
      "signature": {
        "key": "public/signatureImages/2a93893b-7a28-4b83-b5dc-d87df212e53d-signature",
        "url": "https://pricebutlers.s3.us-east-2.amazonaws.com/public/signatureImages/2a93893b-7a28-4b83-b5dc-d87df212e53d-signature",
        "_id": "6687c424512d0ceeacc93170"
      },
      "signatureInfo": true,
      "investorInfo": true,
      "pinNumber": 1234,
      "pinNumberInfo": true,
      "generatedCds": true,
      "passportPic": {
        "key": "public/passportPictures/041dd2f9-75e9-4b98-8a85-e468986d1aa8",
        "url": "https://yanci-uploads.s3.us-east-2.amazonaws.com/public/passportPictures/041dd2f9-75e9-4b98-8a85-e468986d1aa8",
        "_id": "6696179a7d6fdec557143e4e"
      },
      "residentialStatus": "Non-resident Ghanaian",
      "title": "Mr.",
      "policyVersion": 2,
      "termsVersion": 2,
      "status": "pending",
      "countryCode": "+233",
      "phone": "9041409384"
    },
    "address": {
      "_id": "668691a8512d0ceeacc93113",
      "userId": "6685028a6d26699091240d11",
      "country": "India",
      "state": "Punjab",
      "city": "Bathinda",
      "address": "Phase 1",
      "latitude": "0.00",
      "longitude": "0.00",
      "createdAt": "2024-07-04T12:12:24.837Z",
      "updatedAt": "2024-07-16T06:48:29.373Z"
    },
    "beneficiaryPhone": "9041409384"
  }
}
*/

  bool? status;
  UserInfoModelData? data;

  UserInfoModel({
    this.status,
    this.data,
  });
  UserInfoModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    data = (json['data'] != null) ? UserInfoModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
